eureka.client.enabled=false
spring.application.name=auth-service
server.port=8086

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://shared-db:5432/lms_db}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION_MS:86400000}
jwt.refreshExpiration=${JWT_REFRESH_EXPIRATION_MS:604800000}
app.password.pepper=${PASSWORD_PEPPER}
